//! Protocol fees and revenue data
//!
//! Access fees and revenue generated by DeFi protocols.
//!
//! # Example
//!
//! ```no_run
//! # async fn example() -> dllma::error::Result<()> {
//! let client = dllma::Client::new()?;
//!
//! // Get fees overview
//! let fees = client.fees().overview().await?;
//!
//! // Get specific protocol fees
//! let uniswap = client.fees().protocol("uniswap").await?;
//! # Ok(())
//! # }
//! ```

mod api;
mod types;

pub use api::FeesApi;
pub use types::*;
